name: Generate validation profile

on:
  workflow_call:
    inputs:
      profile-path:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - name: Generate wiki files
        run: |
          cd profile-merger
          java -jar profile-merger-1.0-SNAPSHOT.jar 1a
      - name: Commit to veraPDF-corpus.wiki
        uses: drud/action-cross-commit@master
        with:
          source-folder: profile-merger/output
          destination-repository: https://MaximPlusov:${{ secrets.API_TOKEN_GITHUB }}@github.com/MaximPlusov/veraPDF-validation-profiles
          destination-folder: PDF_A
          destination-branch: master
          git-user: "Git User"
          git-commit-message: "Update profiles"
          git-commit-sign-off: "false"
          excludes: .git:Home.md       