name: Push validation profiles

on:
  workflow_call:

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    steps:
      - name: Commit to veraPDF-corpus.wiki
        uses: drud/action-cross-commit@master
        with:
          source-folder: profile-merger/output
          destination-repository: https://MaximPlusov:${{ secrets.WORKFLOW_TOKEN }}@github.com/MaximPlusov/veraPDF-validation-profiles
          destination-folder: .
          destination-branch: master
          git-user: "Git User"
          git-commit-message: "Update profiles"
          git-commit-sign-off: "false"
          excludes: .git:Home.md