name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: |
              cd corpus-wiki-generation
              mkdir output
              java -jar corpus-wiki-generator-1.0-SNAPSHOT.jar
          
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'corpus-wiki-generation/output'
          destination-github-username: 'MaximPlusov'
          destination-repository-name: 'veraPDF-validation-profiles'
          target-branch: integration
