name: Generate validation profile

on:
  workflow_dispatch: 
    inputs:
      pdfa1a:
        required: true
        description: pdfa1a
        type: boolean
      pdfa1b:
        required: true
        description: pdfa1b
        type: boolean    

jobs:
  pdfa1a:
    if: github.event.inputs.pdfa1a == 'true'
    uses: MaximPlusov/veraPDF-tools/.github/workflows/generate-profile.yml@master
    with:
      profile-path: '1a'
      
  pdfa1b:
    if: github.event.inputs.pdfa1b == 'true'
    uses: MaximPlusov/veraPDF-tools/.github/workflows/generate-profile.yml@master
    with:
      profile-path: '1b'
  
  commit-profiles:
    needs: [pdfa1a, pdfa1b]
    name: Commit profiles
    runs-on: ubuntu-20.04
    steps:
      - name: Commit to veraPDF-corpus.wiki
        uses: drud/action-cross-commit@master
        with:
          source-folder: profile-merger/output
          destination-repository: https://MaximPlusov:${{ secrets.WORKFLOW_TOKEN }}@github.com/MaximPlusov/veraPDF-validation-profiles
          destination-folder: .
          destination-branch: master
          git-user: "Git User"
          git-commit-message: "Update profiles"
          git-commit-sign-off: "false"
          excludes: .git:Home.md