name: Update profiles

on:
  workflow_dispatch: 
    inputs:
      pdfa1a:
        required: true
        description: pdfa1a
        type: boolean
      pdfa1b:
        required: true
        description: pdfa1b
        type: boolean    

jobs:
  pdfa1a:
    if: github.event.inputs.pdfa1a == 'true'
    uses: MaximPlusov/veraPDF-tools/.github/workflows/generate-profile.yml@master
    with:
      profile-path: '1a'
      
  pdfa1b:
    if: github.event.inputs.pdfa1b == 'true'
    uses: MaximPlusov/veraPDF-tools/.github/workflows/generate-profile.yml@master
    with:
      profile-path: '1b'
